### ISSUE TITLE
Intellisense should trigger on the character after :

### ISSUE THREAD

**Issue by Tyriar** [mattbierner/vscode-emojisense#1]
Using `:` at the end of a paragraph will trigger the intellisense and insert the 👍 emoji instead of adding a new line. Instead I'd like the popup to appear automatically only on `:+` for `:+1:`, not `:`.

**Comment by mattbierner** [comment]
Yes, I agree that the following cases should never auto trigger suggestions with you type the `:`:

```
a:|
a:| b
```

However for other cases such as:

```
:|
a :|
a :| b
```

I personally like having suggestions triggered without typing a first character. This is also how github inputs work. 

For 0.1.0 I've tried to stop showing completions in those first set of cases. I've also added a `showOnColon` setting that disables automatic triggering on `:` altogether. If you do this, I recommend having quick suggestions enabled or else you have to manually trigger emoji suggestions while typing.

----

Looking into this issue, I ran into a few limitations of our current completion API, including:

* Trigger characters can only be single letters. You cannot register a completion provider that automatically shows after you type `:` and then `c` for example

* Trying to work around the first issue, my next thought was the filter the completion items in the provider so that even if was triggered on `:`, the UI would only start showing emoji results after `c` is typed. As far as I can tell, this is not possible

* No way to tell if a completion provider was triggered by a trigger character or by some other method

Maybe I'm overlooking something simple here but I found that getting the trigger behavior that you described was way harder than it should have been, and the current implementation is still not correct
